[package]
name = "gfastats"
version = "0.1.3"
authors = ["moinSebi <s.vorbrugg@googlemail.com>"]
edition = "2018"
license = "MIT"
description = "GFA statistics"
repository = "https://github.com/MoinSebi/gfastats"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfaR = "=0.1.3"
argparse = "0.2.2"
